spring:
  mail:
    username: unisakurazz@gmail.com
    host: smtp.gmail.com
    password: jg126417~
    port: 587


    properties:
      mail:
        smtp:
          starttls:
            enable=true: