spring:
  boot:
    admin:
      client:
        url: http://localhost:8080
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ssm_db?serverTimezone=UTC
    username: root
    password: jg126417

server:
  port: 80
management:
  endpoint:
    health:
      show-details: always
    info:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"
    enabled-by-default: true

info:
  app:
    name: MyAppName
    version: 1.0.0




mybatis-plus:
  global-config:
    db-config:
      table-prefix: tbl_
      id-type: auto

  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


#iptools:
#  ip:
#    cycle: 1
#    cycle-reset: false
#    model: "detail"

iptool

